# Generated by Django 3.1.3 on 2020-11-22 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('secret', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('secret', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('place', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('tel_num', models.IntegerField()),
                ('acount_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.account')),
            ],
        ),
        migrations.CreateModel(
            name='PlaneType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('capacity', models.IntegerField()),
                ('voyage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VipLevel',
            fields=[
                ('level_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('discount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vip',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
                ('level_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.viplevel')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('arrivePort_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivePort_id', to='app.airport')),
                ('startPort_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='startPort_id', to='app.airport')),
            ],
        ),
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('work_time', models.IntegerField()),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.company')),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.planetype')),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('arrive_time', models.DateTimeField()),
                ('ticketNum', models.IntegerField()),
                ('plane_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.plane')),
                ('route_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.route')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
                ('flight_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.flight')),
            ],
        ),
    ]
