# Generated by Django 3.1.3 on 2020-11-26 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_consign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='flight_id',
        ),
        migrations.AddField(
            model_name='bill',
            name='consign_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.consign'),
            preserve_default=False,
        ),
    ]
