# Generated by Django 2.1.15 on 2020-11-20 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201120_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='id',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
