# Generated by Django 2.1.15 on 2020-11-20 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201120_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='plane',
            name='company_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Company'),
            preserve_default=False,
        ),
    ]
