# Generated by Django 2.1.15 on 2020-11-20 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_plane_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='ticketNum',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
